version: '3'

services:
  nextjs-app:
    image: landingpage
    ports:
      - "3080:80"   # Map port 3080 on host to 80 in the container
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge