version: '3'

services:
  nextjs-app:
    image: landingpage
    container_name: landingpage-dev
    ports:
      - "3080:80"   # Map port 3080 on host to 80 in the container
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge